name: Pilipala Release

# action事件触发
on:
  workflow_dispatch:
  push:
    # push tag时触发
    tags:
      - "v*.*.*"

# 可以有多个jobs
jobs:
  android:
    # 运行环境 ubuntu-latest window-latest mac-latest
    runs-on: ubuntu-latest

    # 每个jobs中可以有多个steps
    steps:
      - name: 代码迁出
        uses: actions/checkout@v3

      - name: 构建Java环境
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
          token: ${{secrets.GIT_TOKEN}}

      - name: 检查缓存
        uses: actions/cache@v2
        id: cache-flutter
        with:
          path: /root/flutter-sdk # Flutter SDK 的路径
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}

      - name: 安装Flutter
        if: steps.cache-flutter.outputs.cache-hit != 'true'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.6
          channel: any

      - name: 下载项目依赖
        run: flutter pub get

# 添加以下步骤
      - name: 打印JAVA Version
        run: java -version

      - name: 打印flutter环境
        run: flutter doctor      
      

      - name: flutter build apk
        run: flutter build apk --release --split-per-abi


      - name: flutter build apk
        run: flutter build apk --release


      - name: 上传 Android 产物
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: build/app/outputs/flutter-apk/*.apk

  iOS:
    runs-on: macos-latest

    steps:
      - name: 代码迁出
        uses: actions/checkout@v4

      - name: 安装Flutter
        if: steps.cache-flutter.outputs.cache-hit != 'true'
        uses: subosito/flutter-action@v2.10.0
        with:
          cache: true
          flutter-version: 3.19.6

      - name: flutter build ipa
        run: |
          flutter build ios --release --no-codesign 
          ln -sf ./build/ios/iphoneos Payload   #  这一步是否有必要你来检查，它创建了一个叫Payload的软链接，你可能不需要
          zip -r9 app.ipa Payload/   #  打包Payload这个文件夹下的runner.app, 生成app.ipa文件

      - name: 上传
        uses: actions/upload-artifact@v3
        with:
          name: Pilipala-Release
          path: build/ios/app.ipa  # 确保这里是你构建的ipa的正确路径
  upload:
    runs-on: ubuntu-latest

    needs:
      - android
      - iOS
    steps:
      - name: 下载 Android 制品
        uses: actions/download-artifact@v3
        with:
          name: android-release
          path: ./android-release    # 下载到 android-release 文件夹

      - name: 下载 iOS 制品
        uses: actions/download-artifact@v3
        with:
          name: Pilipala-Release
          path: ./Pilipala-Release   # 下载到 Pilipala-Release 文件夹
      - name: Install dependencies
        run: sudo apt-get install tree -y

      - name: Get version
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >>$GITHUB_OUTPUT

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          name: v${{ steps.version.outputs.version }}
          token: ${{ secrets.GIT_TOKEN }}
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          allowUpdates: true
          artifacts: |
            android-release/*
            Pilipala-Release/*   # 上传两个文件夹下的所有文件
